// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: uploader_service_uploader.proto

package uploader_service_uploader

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageUploadGrpcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image       []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Section     string `protobuf:"bytes,2,opt,name=section,proto3" json:"section,omitempty"`
	Filename    string `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType string `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
}

func (x *ImageUploadGrpcRequest) Reset() {
	*x = ImageUploadGrpcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uploader_service_uploader_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageUploadGrpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageUploadGrpcRequest) ProtoMessage() {}

func (x *ImageUploadGrpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_uploader_service_uploader_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageUploadGrpcRequest.ProtoReflect.Descriptor instead.
func (*ImageUploadGrpcRequest) Descriptor() ([]byte, []int) {
	return file_uploader_service_uploader_proto_rawDescGZIP(), []int{0}
}

func (x *ImageUploadGrpcRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ImageUploadGrpcRequest) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *ImageUploadGrpcRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ImageUploadGrpcRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type ImageUploadGrpcResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImagePath string `protobuf:"bytes,1,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	Error     []byte `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ImageUploadGrpcResponse) Reset() {
	*x = ImageUploadGrpcResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uploader_service_uploader_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageUploadGrpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageUploadGrpcResponse) ProtoMessage() {}

func (x *ImageUploadGrpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_uploader_service_uploader_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageUploadGrpcResponse.ProtoReflect.Descriptor instead.
func (*ImageUploadGrpcResponse) Descriptor() ([]byte, []int) {
	return file_uploader_service_uploader_proto_rawDescGZIP(), []int{1}
}

func (x *ImageUploadGrpcResponse) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *ImageUploadGrpcResponse) GetError() []byte {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_uploader_service_uploader_proto protoreflect.FileDescriptor

var file_uploader_service_uploader_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x19, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x22, 0x87, 0x01, 0x0a,
	0x16, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x47, 0x72, 0x70, 0x63,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x4e, 0x0a, 0x17, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x47, 0x72, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x86, 0x01, 0x0a, 0x08, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x7a, 0x0a, 0x0f, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x47, 0x72, 0x70, 0x63, 0x12, 0x31, 0x2e, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65,
	0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x65, 0x72, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x47, 0x72,
	0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x75, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x75, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x47, 0x72, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x1d, 0x5a, 0x1b, 0x2e, 0x2f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_uploader_service_uploader_proto_rawDescOnce sync.Once
	file_uploader_service_uploader_proto_rawDescData = file_uploader_service_uploader_proto_rawDesc
)

func file_uploader_service_uploader_proto_rawDescGZIP() []byte {
	file_uploader_service_uploader_proto_rawDescOnce.Do(func() {
		file_uploader_service_uploader_proto_rawDescData = protoimpl.X.CompressGZIP(file_uploader_service_uploader_proto_rawDescData)
	})
	return file_uploader_service_uploader_proto_rawDescData
}

var file_uploader_service_uploader_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_uploader_service_uploader_proto_goTypes = []interface{}{
	(*ImageUploadGrpcRequest)(nil),  // 0: uploader_service_uploader.ImageUploadGrpcRequest
	(*ImageUploadGrpcResponse)(nil), // 1: uploader_service_uploader.ImageUploadGrpcResponse
}
var file_uploader_service_uploader_proto_depIdxs = []int32{
	0, // 0: uploader_service_uploader.Uploader.ImageUploadGrpc:input_type -> uploader_service_uploader.ImageUploadGrpcRequest
	1, // 1: uploader_service_uploader.Uploader.ImageUploadGrpc:output_type -> uploader_service_uploader.ImageUploadGrpcResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_uploader_service_uploader_proto_init() }
func file_uploader_service_uploader_proto_init() {
	if File_uploader_service_uploader_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_uploader_service_uploader_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageUploadGrpcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uploader_service_uploader_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageUploadGrpcResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_uploader_service_uploader_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_uploader_service_uploader_proto_goTypes,
		DependencyIndexes: file_uploader_service_uploader_proto_depIdxs,
		MessageInfos:      file_uploader_service_uploader_proto_msgTypes,
	}.Build()
	File_uploader_service_uploader_proto = out.File
	file_uploader_service_uploader_proto_rawDesc = nil
	file_uploader_service_uploader_proto_goTypes = nil
	file_uploader_service_uploader_proto_depIdxs = nil
}
